# Generated by Django 2.1.7 on 2019-03-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
