# Generated by Django 2.1.7 on 2019-03-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0004_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
