# Generated by Django 2.1.7 on 2019-03-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0008_auto_20190307_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank='TRUE', null='TRUE', upload_to='profile_pics'),
        ),
    ]
