# Generated by Django 2.1.7 on 2019-03-09 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0010_auto_20190307_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remainder', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('trash', models.BooleanField(default=False)),
                ('is_pinned', models.NullBooleanField(default=None)),
                ('label', models.CharField(max_length=50)),
                ('collaborate', models.ManyToManyField(related_name='collaborated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
