# Generated by Django 2.1.7 on 2019-03-13 06:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundoo', '0013_maplabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
        migrations.AddField(
            model_name='notes',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=150, null=True), default=None, null=True, size=None),
        ),
    ]
